Fix frequency unit from 'H' to 'h' for newer Numpy versions
Newer numpy versions use a lowercase "h" instead of "H". When trying to get smaller granular historical data like at 5 seconds, an error would occur:
ValueError: Invalid frequency: 6H. Failed to parse with error message: ValueError("Invalid frequency: H. Failed to parse with error message: KeyError('H'). Did you mean h?")